### ISSUE TITLE
Integration with Dropbox

### ISSUE THREAD

**Issue by webrgp** [quebecstudio/safecraft#2]
Hey there. I've been looking around for a good Craft plugin for backup and I really like yours. The only problem is that it doesn't have dropbox support. Would you be ok if I send a pull request with it?

**Comment by rtrudel** [comment]
If you want to give a hand to improve the plugin, of course :)

**Comment by rtrudel** [comment]
#3 Dropbox destination added. Thanks to@webrgp !
